---
# handlers file for ansible-pf

# sshd job
- name: Unload /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  command: launchctl unload /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  become: yes
  listen: Reload /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  when:
    - ansible_os_family == 'Darwin'
    - pf_ssh_bf_tbl_plist.stat.exists

- name: Load /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  command: launchctl load -w /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  become: yes
  listen: Reload /Library/LaunchDaemons/drew.pf.ssh-bruteforce.expire.plist
  when: ansible_os_family == 'Darwin'


# emerging-threats job
- name: Unload /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  command: launchctl unload /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  become: yes
  listen: Reload /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  when:
    - ansible_os_family == 'Darwin'
    - pf_eto_update_plist.stat.exists

- name: Load /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  command: launchctl load -w /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  become: yes
  listen: Reload /Library/LaunchDaemons/drew.pf.emerging-threats.update.plist
  when: ansible_os_family == 'Darwin'


# pfctl job
- name: Unload /System/Library/LaunchDaemons/com.apple.pfctl.plist
  command: launchctl unload /System/Library/LaunchDaemons/com.apple.pfctl.plist
  become: yes
  listen: Reload pfctl
  when: ansible_os_family == 'Darwin'

- name: Load /System/Library/LaunchDaemons/com.apple.pfctl.plist
  command: launchctl load /System/Library/LaunchDaemons/com.apple.pfctl.plist
  become: yes
  listen: Reload pfctl
  when: ansible_os_family == 'Darwin'
...
